account:
    path:     /
    defaults: { _controller: "AcmebsceneBundle:Account:index" }

account_show:
    path:     /{id}/show
    defaults: { _controller: "AcmebsceneBundle:Account:show" }

account_new:
    path:     /new
    defaults: { _controller: "AcmebsceneBundle:Account:new" }

account_create:
    path:     /create
    defaults: { _controller: "AcmebsceneBundle:Account:create" }
    requirements: { _method: post }

account_edit:
    path:     /{id}/edit
    defaults: { _controller: "AcmebsceneBundle:Account:edit" }

account_update:
    path:     /{id}/update
    defaults: { _controller: "AcmebsceneBundle:Account:update" }
    requirements: { _method: post|put }

account_delete:
    path:     /{id}/delete
    defaults: { _controller: "AcmebsceneBundle:Account:delete" }
    requirements: { _method: post|delete }
