acme_event:
    path:     /
    defaults: { _controller: "AcmebsceneBundle:Event:index" }

acme_event_show:
    path:     /{id}/show
    defaults: { _controller: "AcmebsceneBundle:Event:show" }

acme_event_new:
    path:     /new
    defaults: { _controller: "AcmebsceneBundle:Event:new" }

acme_event_create:
    path:     /create
    defaults: { _controller: "AcmebsceneBundle:Event:create" }
    requirements: { _method: post }

acme_event_edit:
    path:     /{id}/edit
    defaults: { _controller: "AcmebsceneBundle:Event:edit" }

acme_event_update:
    path:     /{id}/update
    defaults: { _controller: "AcmebsceneBundle:Event:update" }
    requirements: { _method: post|put }

acme_event_delete:
    path:     /{id}/delete
    defaults: { _controller: "AcmebsceneBundle:Event:delete" }
    requirements: { _method: post|delete }
